<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.sonarsource.parent</groupId>
    <artifactId>parent</artifactId>
    <version>79.0.0.2165</version>
  </parent>

  <groupId>org.sonarsource.groovy</groupId>
  <artifactId>groovy</artifactId>
  <version>${revision}</version>
  <packaging>pom</packaging>

  <properties>
    <orchestrator.version>3.11</orchestrator.version>
	    <!-- 
		voir https://github.com/SonarSource/sonar-plugin-api?tab=readme-ov-file#compatibility 
		pour connaitre la version de l'API par rapport à la version de sonarqube
		-->
		<sonar-plugin-api>10.14.0.2599</sonar-plugin-api>
		<sonar-plugin-api-impl>24.12.0.100206</sonar-plugin-api-impl>
        <sonar.lang.patterns.grvy>**/*.groovy</sonar.lang.patterns.grvy>
    <revision>10.8.1</revision>
  </properties>

  <name>Sonar Groovy</name>
  <description>This plugin enables analysis of Groovy within SonarQube.</description>
  <url>http://redirect.sonarsource.com/plugins/groovy.html</url>
  <inceptionYear>2010</inceptionYear>
  <organization>
    <name>SonarQube Community</name>
  </organization>
  <licenses>
    <license>
      <name>GNU LGPL 3</name>
      <url>http://www.gnu.org/licenses/lgpl.txt</url>
      <distribution>repo</distribution>
    </license>
  </licenses>

  <developers>
    <developer>
      <id>TobiX</id>
      <name>Tobias Gruetzmacher</name>
    </developer>
  </developers>
  <contributors>
    <contributor>
      <name>Patrick Mayweg</name>
    </contributor>
    <contributor>
      <name>Michael Gumowski</name>
    </contributor>
    <contributor>
      <name>Nicolas Peru</name>
    </contributor>
  </contributors>

  <modules>
    <module>sonar-groovy-plugin</module>
    <module>codenarc-converter</module>
  </modules>

  <scm>
    <connection>scm:git:git@github.com:forge-MAIF/sonar-groovy.git</connection>
    <developerConnection>scm:git:git@github.com:forge-MAIF/sonar-groovy.git
    </developerConnection>
    <url>https://github.com/forge-MAIF/sonar-groovy/tree/main</url>
    <tag>HEAD</tag>
  </scm>
  <issueManagement>
    <system>GitHub</system>
    <url>https://github.com/forge-MAIF/sonar-groovy/issues</url>
  </issueManagement>
  <ciManagement>
    <system>github-actions</system>
    <url>https://github.com/forge-MAIF/sonar-groovy/actions</url>
  </ciManagement>
  <distributionManagement>
    <repository>
      <id>github</id>
      <name>GitHub Packages</name>
      <url>https://maven.pkg.github.com/forge-MAIF/sonar-groovy</url>
      <uniqueVersion>false</uniqueVersion>
    </repository>
  </distributionManagement>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.sonarsource.api.plugin</groupId>
        <artifactId>sonar-plugin-api</artifactId>
        <version>${sonar-plugin-api}</version>
        <scope>provided</scope>
      </dependency>
      <dependency>
        <groupId>org.sonarsource.sonarqube</groupId>
        <artifactId>sonar-plugin-api-impl</artifactId>
        <version>${sonar-plugin-api-impl}</version>
        <scope>test</scope>
      </dependency>
      <dependency>
        <groupId>org.codenarc</groupId>
        <artifactId>CodeNarc</artifactId>
        <version>2.2.0</version>
        <exclusions>
          <exclusion>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-ant</artifactId>
          </exclusion>
        </exclusions>
      </dependency>
      <dependency>
        <groupId>org.gmetrics</groupId>
        <artifactId>GMetrics</artifactId>
        <version>1.1</version>
        <exclusions>
          <exclusion>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-ant</artifactId>
          </exclusion>
        </exclusions>
      </dependency>
      <dependency>
        <groupId>commons-io</groupId>
        <artifactId>commons-io</artifactId>
        <version>2.11.0</version>
      </dependency>
      <dependency>
        <groupId>commons-lang</groupId>
        <artifactId>commons-lang</artifactId>
        <version>2.6</version>
      </dependency>
      <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-simple</artifactId>
        <version>1.7.36</version>
      </dependency>

      <dependency>
        <groupId>junit</groupId>
        <artifactId>junit</artifactId>
        <version>4.13.2</version>
        <scope>test</scope>
      </dependency>
      <dependency>
        <groupId>org.assertj</groupId>
        <artifactId>assertj-core</artifactId>
        <version>3.21.0</version>
        <scope>test</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <repositories>
    <repository>
      <id>github</id>
      <name>GitHub Packages</name>
      <url>https://maven.pkg.github.com/forge-MAIF/sonar-groovy</url>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
    </repository>
  </repositories>

  <build>
    <plugins>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>flatten-maven-plugin</artifactId>
        <version>1.5.0</version>
        <executions>
          <execution>
            <id>flatten</id>
            <phase>process-resources</phase>
            <goals>
              <goal>flatten</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>com.diffplug.spotless</groupId>
        <artifactId>spotless-maven-plugin</artifactId>
        <version>2.43.0</version>
        <executions>
          <execution>
            <goals>
              <goal>check</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <!-- get better with time -->
          <ratchetFrom>origin/main</ratchetFrom>
          <formats>
            <format>
              <includes>
                <include>*.md</include>
                <include>.gitignore</include>
              </includes>
              <trimTrailingWhitespace />
              <endWithNewline />
              <indent>
                <spaces>true</spaces>
                <spacesPerTab>4</spacesPerTab>
              </indent>
            </format>
          </formats>
          <java>
            <licenseHeader>
              <file>LICENSE-header-java.txt</file>
            </licenseHeader>
            <googleJavaFormat />
          </java>
        </configuration>
      </plugin>
      <plugin>
        <groupId>com.mycila</groupId>
        <artifactId>license-maven-plugin</artifactId>
        <version>4.1</version>
        <configuration>
          <skip>true</skip>
        </configuration>
      </plugin>
    </plugins>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.sonarsource.scanner.maven</groupId>
          <artifactId>sonar-maven-plugin</artifactId>
          <version>3.9.1.2184</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-source-plugin</artifactId>
          <version>3.2.1</version>
          <executions>
            <execution>
              <configuration>
                <attach>false</attach>
              </configuration>
              <goals>
                <goal>jar-no-fork</goal>
              </goals>
            </execution>
          </executions>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
</project>
